### ISSUE TITLE
Similar ideas

### ISSUE THREAD

**Issue by mountain** [Dominux/DGS#43]
Hi, Dominux,

I just found your project, it is amazing that we have similar ideas, but I started the project later than you.
* https://github.com/spherical-go/polyclash

You can found my contact on github profile page, let's talk and exchange the ideas.

Mingli

**Comment by Dominux** [comment]
Sup fellow korean. Why the heck did you use python for that? And using Flask in 2024? I thought vietnamies are overminds, but that idea of yours doesn't seem to be intelligent at all
